### ISSUE TITLE
Running without segmentation map

### ISSUE THREAD

**Issue by jmhong-simulation** [codeslake/Color_Transfer_Histogram_Analogy#2]
Hi!
The results are beautiful and stable!
The limitation section states that your method can work without semantic replacement.
Is there an option to turn it off?
Thank you!

**Comment by codeslake** [comment]
Hi :)

Would you try following line?
`python test.py --dataroot [test folder path] --checkpoints_dir [ckpt path] --is_SR`

I believe `--is_SR` will turn of semantic replacement.

Thanks.

**Comment by jmhong-simulation** [comment]
I'm still getting an error message as follows after placing test images under ./test/input and ./test/target while leaving seg_in and seg_tar empty.

(pytorch) jmhong@jmhong-dual:~/git-repo/Color_Transfer_Histogram_Analogy$ python test.py --dataroot ./test --checkpoints_dir ./checkpoints/ --is_SR
/home/jmhong/git-repo/Color_Transfer_Histogram_Analogy/models/networks.py:17: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 0.0, 0.02)
/home/jmhong/git-repo/Color_Transfer_Histogram_Analogy/models/networks.py:19: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 0.0, 0.02)
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    for i, data in enumerate(dataset):
  File "/home/jmhong/git-repo/Color_Transfer_Histogram_Analogy/data/custom_dataset_data_loader.py", line 33, in __iter__
    for i, data in enumerate(self.dataloader):
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jmhong/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jmhong/git-repo/Color_Transfer_Histogram_Analogy/data/aligned_dataset_rand_seg_onlymap.py", line 41, in __getitem__
    A_path_map = self.A_paths_map[index % self.A_size]
IndexError: list index out of range

**Comment by sownds7** [comment]
I am facing issue while running test.py ,
Folder structure : ./test folder has  ./test/input and ./test/target
Cmd used: !python test.py --dataroot './test' --checkpoints_dir './checkpoints' --is_SR

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/data_loader.py", line 5, in CreateDataLoader
    data_loader.initialize(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/custom_dataset_data_loader.py", line 19, in initialize
    self.dataset = CreateDataset(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/custom_dataset_data_loader.py", line 8, in CreateDataset
    dataset.initialize(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/aligned_dataset_rand_seg_onlymap.py", line 26, in initialize
    self.A_paths_map = make_dataset(self.dir_A_Map)
  File "/content/Color_Transfer_Histogram_Analogy/data/image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ./test/seg_in is not a valid directory

**Comment by codeslake** [comment]
@jmhong-simulation 

Are you using pytorch 0.4.0?
I've cloned the source codes and ran it with `--SR` option, but it works fine.

You might have to check whether the number for input, target, and segmentation maps for each of them are the same.

Best,

**Comment by codeslake** [comment]
@sownds7 

will you try `python test.py --dataroot test --checkpoints_dir checkpoints --is_SR`?

**Comment by sownds7** [comment]
@codeslake , Yes I tried running the above command with just input & target folder. Still getting same error.

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/data_loader.py", line 5, in CreateDataLoader
    data_loader.initialize(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/custom_dataset_data_loader.py", line 19, in initialize
    self.dataset = CreateDataset(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/custom_dataset_data_loader.py", line 8, in CreateDataset
    dataset.initialize(opt)
  File "/content/Color_Transfer_Histogram_Analogy/data/aligned_dataset_rand_seg_onlymap.py", line 26, in initialize
    self.A_paths_map = make_dataset(self.dir_A_Map)
  File "/content/Color_Transfer_Histogram_Analogy/data/image_folder.py", line 26, in make_dataset
    assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: test/seg_in is not a valid directory

**Comment by codeslake** [comment]
@sownds7 

Is `test/seg_in` a directory?
Segmentation maps of input images should be placed under `test/seg_in`.
For target images, segmentation maps should be placed under `test/seg_tar`.

As I mentioned earlier, I've cloned this repository to make sure whether there were any mistakes during organizing the codes for the release, but I couldn't find any error while running the code.
Please be sure that the folder structure is correct as described in the README.

Best,

**Comment by sownds7** [comment]
@codeslake 

Yes test/seg_in is a directory.  

As per the limitations mentioned in the paper :  _a user may simply turn off semantic
replacement as our method can still provide natural-looking results without semantic replacement.__

So I assume that segmentations maps ie folders test/seg_in and test/seg_tar aren't needed when we run this 'python test.py --dataroot test --checkpoints_dir checkpoints --is_SR' script. 

Please advise if I am wrong. 

Thanks!

**Comment by codeslake** [comment]
@sownds7 

Oh, I got your point!
just copy and paste the images in `test/input` to `test/seg_in`, and do the same for `test/target` and `test/set_tar`.

The error occurs because the dataloader is coded to read the segmentation maps. I will modify the code ASAP.
`--is_SR` option will ignore images in `test/seg_in` and `test/seg_tar`.

Thanks for the comment!

**Comment by sownds7** [comment]
@codeslake Thankyou so much ! :)

**Comment by codeslake** [comment]
@sownds7 @jmhong-simulation 

Will you guys pull the repository and try it again?
Best,

**Comment by sownds7** [comment]
@codeslake Thanks 'python test.py --dataroot test --checkpoints_dir checkpoints --is_SR' works for me.

**Comment by codeslake** [comment]
Closing the issue. @jmhong-simulation, please open an issue if the error continues :)
